name: Murder
version: '1.0'
main: Aximox.murder.Murder
api-version: '1.21'
authors: [ Aximoxx ]
commands:
  setrank:
    description: Défini le status des joueurs.
  murder:
    description: fait toute les commandes du murder
  doc:
    description: donne le doc
